@startuml

class GameMaster {
    -int screenWidth;
    -int screenHeight;
    -raylib::Window window;
    -raylib::Texture background_texture;
    -int fontSize;

    -Spaceship ship;

    -std::vector<Bullet> bullets{};
    -float bulletCooldown;
    -float timeSinceLastShot;

    -float asteroidCooldown;
    -float timeSinceLastAsteroid;
    -std::vector<Asteroid> asteroids{};

    -int lifes;
    -int score;

    +GameMaster();
    +void manageGame();
    -void createAsteroids();
    -void handleKeyboardInput();
}

class GameObject {
    -float x;
    -float y;
    -float vel_x;
    -float vel_y;
    -float direction;
    -double speed;
    -raylib::Texture texture;
    +get_x();
    +get_y();
    -move();
    -draw();
    -rotate();
}

class Bullets {
}

class SpaceShip {
}

class Targets {
}


SpaceShip --|> GameObject
Targets --|> GameObject
Bullets --|> GameObject

GameObject --|> GameMaster

@enduml