@startuml

class GameMaster {
    checkForColissions();
    createBullet();
    createTarget();
    checkSpaceshipLifes();
}

class GameObject {
    -float x;
    -float y;
    -float vel_x;
    -float vel_y;
    -float direction;
    -double speed;
    -raylib::Texture texture;
    +get_x();
    +get_y();
    -move();
    -draw();
    -rotate();
}

class Bullets {
}

class SpaceShip {
}

class Targets {
}


SpaceShip --|> GameObject
Targets --|> GameObject
Bullets --|> GameObject

GameObject --|> GameMaster

@enduml